backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
collections:
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: 'HH:mm:ss'
        format: 'YYYY-MM-DD HH:mm:ss'
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: about-index.md
        label: 我的小秘密
        file: source\about\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: gallery-Genshin Impact.md
        label: 元神
        file: source\gallery\Genshin Impact.md
        editor:
          preview: true
        fields: *ref_0
      - name: categories-index.md
        label: 分类
        file: source\categories\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: gallery-Onmyoji.md
        label: 阴阳师
        file: source\gallery\Onmyoji.md
        editor:
          preview: true
        fields: *ref_0
      - name: gallery-index.md
        label: 图片
        file: source\gallery\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: gallery-World of Warcraft.md
        label: 魔兽世界
        file: source\gallery\World of Warcraft.md
        editor:
          preview: true
        fields: *ref_0
      - name: gallery-lol.md
        label: 英雄联盟
        file: source\gallery\lol.md
        editor:
          preview: true
        fields: *ref_0
      - name: movies-index.md
        label: 视频
        file: source\movies\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: tags-index.md
        label: 标签
        file: source\tags\index.md
        editor:
          preview: true
        fields: *ref_0
